require('dotenv').config();

const TRIAL_DAYS = 7;

const PRICES = {
  SUPER_LIKE: parseInt(process.env.SUPER_LIKE_AMOUNT || '500'),
  DIRECT_MESSAGE: parseInt(process.env.DIRECT_MESSAGE_AMOUNT || '500'),
  BOOST_1D: parseInt(process.env.BOOST_1D_AMOUNT || '1000'),
  BOOST_3D: parseInt(process.env.BOOST_3D_AMOUNT || '2500'),
  BOOST_7D: parseInt(process.env.BOOST_7D_AMOUNT || '5000'),
  GOLDEN_ROSE: parseInt(process.env.GOLDEN_ROSE_AMOUNT || '2500'),
  ROSE_NOTE_UNLOCK: parseInt(process.env.ROSE_NOTE_UNLOCK_AMOUNT || '500')
};

const PLAN_AMOUNTS = {
  MONTHLY: parseInt(process.env.PLAN_MONTHLY_AMOUNT || '5000'),
  QUARTERLY: parseInt(process.env.PLAN_QUARTERLY_AMOUNT || '10000')
};

const PARTNER_PLAN_AMOUNTS = {
  VISIBILITY: parseInt(process.env.PARTNER_VISIBILITY_AMOUNT || '25000'),
  PRESTIGE: parseInt(process.env.PARTNER_PRESTIGE_AMOUNT || '50000')
};

const QUOTAS = {
  FREE_MALE_DAILY_SWIPES: 10,
  GALANTERIE_BONUS_SWIPES: 5,
  GALANTERIE_THRESHOLD: 4.7,
  WOMEN_SUPER_LIKE: 10,
  MEN_3M_INVISIBLE_VIEWS: 20,
  MEN_3M_STATUS_VIEWS: 20,
  DAILY_BOOST_SECONDS: 3600,
  MEN_3M_HIDE_SEEN_SECONDS: 7200,
  TRIAL_BOOST_SECONDS: 3600
};

const BOOST_SCORES = {
  '1D': 500,
  '3D': 700,
  '7D': 1000,
  'FREE': 500
};

const PLAN_DURATIONS = {
  MONTHLY: 30,
  QUARTERLY: 90,
  VISIBILITY: 30,
  PRESTIGE: 30
};

const ALLOWED_REPORT_REASONS = new Set([
  'GENERAL',
  'FAKE_PROFILE',
  'HARASSMENT',
  'SPAM',
  'SCAM',
  'INAPPROPRIATE_CONTENT',
  'VIOLENCE',
  'OTHER',
]);

module.exports = {
  TRIAL_DAYS,
  PRICES,
  PLAN_AMOUNTS,
  PARTNER_PLAN_AMOUNTS,
  QUOTAS,
  BOOST_SCORES,
  PLAN_DURATIONS,
  ALLOWED_REPORT_REASONS,
  STORY_LIKE_NOTIFICATION_DEDUP_MS: 60 * 1000
};
